var mobile=jQuery.browser.mobile,xs=767<$(window).width()?!1:!0;$(window).load(function(){$.cookie("PS4U[return]")||($(".js-page-loader").addClass("page-loader--animated"),setTimeout(function(){$("body").removeClass("unloaded");$(".js-main-carousel").carousel({interval:6E3});setTimeout(function(){$("body").removeClass("preloader-is-visible");$(".js-page-loader").remove();$.cookie("PS4U[return]",!0,{expires:1})},1500)},2E3))});
$(function(){var a=$(window).scrollTop(),b=$(".js-main-navbar"),c=$(".js-main-navbar-breakpoint"),d=$(".js-main-carousel-scrolldown-arrow").offset().top-b.outerHeight();$(window).scroll(function(){a=$(window).scrollTop();100<a?b.addClass("main-navbar--scrolled"):b.removeClass("main-navbar--scrolled");a>c.offset().top-b.outerHeight()?b.addClass("main-navbar--darker"):b.removeClass("main-navbar--darker");a>=c.offset().top+c.outerHeight()-b.outerHeight()?b.addClass("main-navbar--border"):(b.removeClass("main-navbar--border"),
    $(".js-navbar-menu-url--main").parent().removeClass("main-navbar__menu-el--active"),removeUrlHash());a>=d?$(".js-main-carousel-scrolldown-arrow").addClass("main-carousel__scrolldown-arrow--hidden"):$(".js-main-carousel-scrolldown-arrow").removeClass("main-carousel__scrolldown-arrow--hidden");$(".js-slide").each(function(c){c=$(this).attr("id");var d=$('.js-navbar-menu-url--main[href="#'+c+'"]').parent();$(this).position().top<=a+b.outerHeight()&&($(".js-navbar-menu-url--main").parent().not(d).removeClass("main-navbar__menu-el--active"),
    d.addClass("main-navbar__menu-el--active"),mobile||(history.pushState?history.pushState(null,null,"#"+c):window.location.hash="#"+c))});mobile||ctaScroll(a,c)}).scroll();mobile||($(document).on("mousemove",function(b){ctaScroll(a,c)}),$(document).on("click",function(b){ctaScroll(a,c)}),$(document).on("keydown",function(b){jQuery.inArray(b.which,[37,38,39,40])&&ctaScroll(a,c)}));$(".js-go-to-section").on("click",function(a){a.preventDefault();a=$(this).data("goto")?$(this).data("goto"):$(this).attr("href");
    var b=$(this).attr("href")?$(this).attr("href"):null,c=$(this).data("goto-smooth")?$(this).data("goto-smooth"):null;slideToSection(a,b,c)});window.location.hash&&slideToSection(window.location.hash)});
$(function(){$(window).resize(function(){xs&&($(".js-service-nav").on("click",function(){slideToSection(".js-slide-content--services","#services",!0)}),$(".js-comparison-twentytwenty--animation-not-stared").on("click",function(){slideToSection(".js-comparison","#about",!0,20)}));$(".js-comaprison-summation-col").css("height",$(".js-twentytwenty-img").height())}).resize()});
function ctaScroll(a,b){$(".js-cta-scroll").addClass("cta--hidden");clearTimeout($.data(this,"scrollCheck"));var c=$(".js-slide--experience").offset().top+$(".js-slide--experience").height()-$(window).height();a>b.offset().top&&a<c&&$.data(this,"scrollCheck",setTimeout(function(){$(".js-cta-scroll").removeClass("cta--hidden")},3E3))}
function slideToSection(a,b,c,d){b=b||null;c=c||null;d=d||null;a="start"==a?0:$(a).offset().top-$(".js-main-navbar").height()+d;c?$("html, body").animate({scrollTop:a},c):$("html, body").scrollTop(a);mobile||(b?history.pushState?history.pushState(null,null,b):window.location.hash=b:removeUrlHash())}
function removeUrlHash(){var a=window.location;if("pushState"in history)history.pushState("",document.title,a.pathname+a.search);else{var b=document.body.scrollTop;var c=document.body.scrollLeft;a.hash="";document.body.scrollTop=b;document.body.scrollLeft=c}}
$(function(){$(".js-comparison-twentytwenty-init").twentytwenty({default_offset_pct:1});$(".js-comparison-twentytwenty").on("mouseenter",".js-comparison-twentytwenty--animation-not-stared",function(){$(window).trigger("animate.twentytwenty");$(".js-cta-comparison-start").addClass("cta--hidden")})});autosize(document.querySelectorAll(".js-autosize"));
$(function(){mobile||xs||($(".main-contact__form-control").on("focus",function(){$(".js-main-contact-box").addClass("main-contact__contact-box--extended-form");$(".js-main-contact-form-collapse-btn").delay(100).queue(function(){$(this).addClass("main-contact__form-collapse-btn--static").dequeue()})}),$(".js-main-contact-form-collapse-btn").on("click",function(){$(".js-main-contact-box").removeClass("main-contact__contact-box--extended-form");$(this).delay(600).queue(function(){$(this).removeClass("main-contact__form-collapse-btn--static").dequeue()})}))});
$(function(){$(".js-portfolio-slider").slick({lazyLoad:"ondemand",slidesToShow:1,slidesToScroll:1,fade:!0,asNavFor:".js-portfolio-slider-thumbs",appendArrows:".js-portfolio-slider-arrows",prevArrow:'<span class="[ nav-arrow  nav-arrow--left-maroon-large ]  [ portfolio-slider__arrow--left"></span>',nextArrow:'<span class="[ nav-arrow  nav-arrow--right-maroon-large ]  [ portfolio-slider__arrow--right"></span>'});$(".js-portfolio-slider-thumbs").slick({lazyLoad:"ondemand",slidesToShow:3,slidesToScroll:1,
    asNavFor:".js-portfolio-slider",arrows:!1,centerMode:!0,centerPadding:0,draggable:!1,focusOnSelect:!0})});$(function(){$("#services-carousel").on("slid.bs.carousel",function(){currentSlide=$(".js-service-nav.active").index()+1;$(".js-services-carousel-indicators").attr("data-current-slide",currentSlide)})});$(function(){mobile&&($(".carousel").swiperight(function(){$(this).carousel("prev")}),$(".carousel").swipeleft(function(){$(this).carousel("next")}))});
$(function(){$(".js-main-contact-form").on("submit",function(a){a.preventDefault();var b=$(this),c;$("input,textarea",b).filter("[required]:visible").each(function(){simpleValidator($(this))});$.post("/",b.serialize(),function(a){"1"==a.type?c="success":"2"==a.type&&(c="danger");$(".js-main-contact-form-alert").length||b.prepend('<div class="[ row ]  [ js-main-contact-form-alert ]"><div class="col-lg-12"><div class="[ main-contact__form-alert ]  ][ alert  alert-'+c+' ]">'+a.message+"</div></div></div>")})});
    $(".js-main-contact-form").on("change",".main-contact__form-control--error",function(){simpleValidator($(this))})});
function simpleValidator(a){var b=/^([a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+(\.[a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+)*|"((([ \t]*\r\n)?[ \t]+)?([\x01-\x08\x0b\x0c\x0e-\x1f\x7f\x21\x23-\x5b\x5d-\x7e\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|\\[\x01-\x09\x0b\x0c\x0d-\x7f\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))*(([ \t]*\r\n)?[ \t]+)?")@(([a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.)+([a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.?$/i;var c=
    0<$.trim(a.val()).length?!1:!0;a.filter('[type="email"]').length&&(c=b.test(a.val())?!1:!0);c?a.addClass("main-contact__form-control--error"):a.removeClass("main-contact__form-control--error");$(".main-contact__form-control--error").length||$(".js-main-contact-form-alert.danger").remove()};